export const Categories = {
    coding : [
  "coding",
  "programming",
  "software development",
  "developer",
  "web development",
  "full stack",
  "frontend",
  "backend",
  "javascript",
  "python",
  "java",
  "c++",
  "nodejs",
  "expressjs",
  "mongodb",
  "html",
  "css",
  "api development",
  "data structures",
  "computer science",
  "machine learning",
  "tech",
  "coding tutorial",
  "programming tutorial",
  "project tutorial",
  "bug fixing",
  "debugging",
  "open source",
  "clean code",
  "software engineer",
  "learn to code",
  "build projects",
  "coding playlist",
  "internship",
  "intern",
  "placements",
  "jobs",
  "leetcode",
  "codeforces",
]
,
    music : [
  "music",
  "new music",
  "trending music",
  "viral song",
  "viral music",
  "best music",
  "music video",
  "audio",
  "official music",
  "remix",
  "slowed + reverb",
  "sped up",
  "bass boosted",
  "lofi",
  "beats",
  "instrumental",
  "hip hop",
  "trap",
  "pop music",
  "edm",
  "electronic",
  "rock",
  "chill music",
  "aesthetic music",
  "motivation music",
  "workout music",
  "background music",
  "cinematic music",
  "edit audio",
  "edit song",
  "edit music",
  "viral edit audio",
  "trending edit audio",
  "transition edit",
  "beat sync",
  "perfect beat drop",
  "hard bass",
  "aesthetic edit",
  "cinematic edit",
  "fan edit",
  "sports edit audio",
  "youtube shorts",
  "shorts",
  "reels music",
  "tiktok music",
  "viral reels audio",
  "trending shorts sound"
]
,
    fitness : [
  "fitness",
  "workout",
  "gym",
  "gym motivation",
  "fitness motivation",
  "workout motivation",
  "bodybuilding",
  "muscle building",
  "fat loss",
  "weight loss",
  "calisthenics",
  "strength training",
  "cardio",
  "hiit workout",
  "full body workout",
  "upper body workout",
  "leg day",
  "abs workout",
  "core workout",
  "gym edit",
  "fitness edit",
  "workout edit",
  "gym transformation",
  "fitness transformation",
  "gym lifestyle",
  "healthy lifestyle",
  "diet",
  "nutrition",
  "fitness journey",
  "training",
  "athlete",
  "gym vlog",
  "fitness reels",
  "fitness shorts",
  "gym reels",
  "motivational fitness",
  "fitness tips",
  "fitness music",
  "workout beats",
  "workout routine",
  "fitness challenge"
]
,
gaming : [
  "gaming",
  "esports",
  "gameplay",
  "pro gameplay",
  "competitive gaming",
  "pc gaming",
  "mobile gaming",
  "console gaming",
  "gaming highlights",
  "gaming montage",
  "gaming edit",
  "esports edit",
  "esports highlights",
  "gaming shorts",
  "gaming reels",
  "gaming clip",
  "funny gaming",
  "fps gaming",
  "battle royale",
  "multiplayer",
  "live gameplay",
  "game review",
  "gaming community",
  "gamer",
  "pro gamer",
  "gaming setup",
  "gaming tips",
  "gaming tricks",
  "aim training",
  "reaction time",
  "best moment",
  "epic moment",
  "clutch moment",
  "pro plays",
  "insane gameplay",
  "headshot",
  "tournament",
  "ranked match",
  "gaming vibe",
  "gaming music",
  "no commentary",
  "walkthrough",
  "speedrun"
]
}
